sudo: true

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
            - wget
            - clang

before_install:
    - sudo apt-get install valgrind libcurl4-openssl-dev
    - sudo pip install codecov


install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

before_script:
    - echo $CC
    - echo $CXX
    - $CXX --version
    - $CC --version
    - cmake --version


script:
    - cmake .
    - make
    - valgrind ./tests_hermes
    - gcov-5 tests/unix/main.cpp

after_success:
    - bash <(curl -s https://codecov.io/bash)
