sudo: true

language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

        packages:
            - gcc-4.8
            - g++-4.8
            - clang
            - wget

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -H apt-get install valgrind libcurl4-openssl-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo -H pip install codecov; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48 --enable-cxx; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install g++48 llvm --with-clang; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi

install:
    - if [ "CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
    - cmake --version


script:
    - cmake .
    - make
    - valgrind ./tests_hermes
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gcov-5 tests/unix/main.cpp; fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
